# Generated by Django 3.2.12 on 2022-04-04 22:22

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        help_text="Slug will be automaticaly set from forum title.",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Write your question here.", verbose_name="Question"
                    ),
                ),
                ("enable_comments", models.BooleanField(default=True)),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated on"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Choose a category for this question. +<a href='/forum/s/category/add' target='_blank'>Add new category</a>",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forums",
                        to="blog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "questioner",
                    models.ForeignKey(
                        help_text="The user who asked the question.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="questioner",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="Describe what this question is about. Separate tags with commas. Use existing tags or add new ones. +<a href='/forum/s/tag/add' target='_blank'>Add new tag</a>",
                        related_name="forums",
                        to="blog.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "votes",
                    models.ManyToManyField(
                        related_name="voted_forums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Votes",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum",
                "verbose_name_plural": "forums",
                "db_table": "forum",
                "permissions": [("can_vote_answer", "Can vote answer")],
            },
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["slug"], name="forum_slug_idx"),
        ),
    ]
