"""auser utilities

    Generated by: Wendirad Demelash
    Last modified by: Wendirad Demelash
"""
import os


def generate_username(length=6):
    """Generate a random username of length 10."""
    return os.urandom(length // 2).hex()
