# Generated by Django 3.2.12 on 2022-05-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site'),
        ),
    ]
